-- 제약조건

-- NOT NULL
DESC DEPARTMENTS;

-- UK
CREATE TABLE EMP1 (
ENO NUMBER(3),
EMP_NAME VARCHAR2(20) CONSTRAINT EMP1_ENAME_NN NOT NULL,
EMAIL VARCHAR2(30),
CONSTRAINT EMP1_EMAIL_UK UNIQUE (EMAIL)
);

INSERT INTO EMP1 VALUES(208, 'KIM', 'KJS@NAVER.COM');
INSERT INTO EMP1 VALUES(209, NULL, 'ABC@NAVER.COM');
INSERT INTO EMP1 VALUES(210, 'LEE', 'KJS@NAVER.COM');

-- CHECK 제약조건
CREATE TABLE EMP2 (
ENO NUMBER(3),
EMP_NAME VARCHAR2(20) ,
SAL NUMBER(10),
CONSTRAINT EMP2_SAL_CHECK CHECK(SAL>1000)
);

INSERT INTO EMP2 VALUES (208, 'KIM', 1200);
INSERT INTO EMP2 VALUES (209, 'LEE', 900);

-- 제약조건 이름 없이 테이블 생성
DROP TABLE EMP;
CREATE TABLE EMP (
ENO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(20) NOT NULL,
GNO VARCHAR2(13) UNIQUE CHECK (LENGTH(GNO) >= 8),
GENDER VARCHAR2(5) CHECK (GENDER IN('WOMAN', 'MAN'))
);

INSERT INTO EMP VALUES(1, 'KIM', '12345678', 'MAN');
INSERT INTO EMP VALUES(2, 'KIM', '123456789', 'WOMAN');

-- 예제
CREATE TABLE MEMBERS (
MEMBER_ID NUMBER(2) PRIMARY KEY,
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
GENDER VARCHAR2(5) CHECK (GENDER IN('WOMAN', 'MAN')),
BIRTH_DAY DATE DEFAULT SYSDATE,
EMAIL VARCHAR2(200) UNIQUE NOT NULL
);