-- SCOTT 연습문제

--SCOTT EMP 테이블
SELECT *
FROM EMP;

-- 문제 1
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 10;

-- 문제 2
SELECT ENAME, HIREDATE, DEPTNO
FROM EMP
WHERE EMPNO = 7369;

-- 문제 3
SELECT *
FROM EMP
WHERE ENAME = 'ALLEN';

-- 문제 4
SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE HIREDATE = '81/02/20';

-- 문제 5
SELECT *
FROM EMP
WHERE JOB != 'MANAGER';

-- 문제 6
SELECT *
FROM EMP
WHERE HIREDATE >= '81/04/02';

-- 문제 7
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL >= 800;

-- 문제 8
SELECT *
FROM EMP
WHERE DEPTNO >= 20;

-- 문제 9
SELECT *
FROM EMP
WHERE ENAME > 'L';

-- 문제 10
SELECT *
FROM EMP
WHERE HIREDATE < '81/12/09';

-- 문제 11
SELECT EMPNO, ENAME
FROM EMP
WHERE EMPNO <= 7698;

-- 문제 12
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE HIREDATE BETWEEN '81/04/02' AND '82/12/09';

-- 문제 13
SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL > 1600 AND SAL < 3000;

-- 문제 14
SELECT *
FROM EMP
WHERE NOT (EMPNO >= 7654 AND EMPNO <= 7782);

-- 문제 15
SELECT *
FROM EMP
WHERE ENAME >= 'B' AND ENAME <= 'J';

-- 문제 16
SELECT *
FROM EMP
WHERE TRUNC(HIREDATE, 'YEAR') != '81/01/01';

-- 문제 17
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN';

-- 문제 18
SELECT ENAME, EMPNO, DEPTNO
FROM EMP
WHERE DEPTNO != 20 AND DEPTNO != 30;

-- 문제 19
SELECT EMPNO, ENAME, HIREDATE, DEPTNO
FROM EMP
WHERE ENAME LIKE 'S%';

-- 문제 20
SELECT *
FROM EMP
WHERE TRUNC(HIREDATE, 'YEAR') = '81/01/01';

-- 문제 21
SELECT *
FROM EMP
WHERE ENAME LIKE '%S%';

-- 문제 22
SELECT *
FROM EMP
WHERE ENAME LIKE 'M____N';

-- 문제 23
SELECT *
FROM EMP
WHERE ENAME LIKE '_A%';

-- 문제 24
SELECT *
FROM EMP
WHERE COMM IS NULL;

-- 문제 25
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

-- 문제 26
SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE DEPTNO = 30 AND SAL >= 1500;

-- 문제 27
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE ENAME LIKE 'K%' OR DEPTNO = 30;

-- 문제 28
SELECT *
FROM EMP
WHERE SAL >= 1500 AND DEPTNO = 30 AND JOB = 'MANAGER';

-- 문제 29
SELECT *
FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO;

-- 문제 30
SELECT *
FROM EMP
ORDER BY SAL DESC;

-- 문제 31
SELECT *
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

-- 문제 32
SELECT DEPTNO, ENAME, SAL
FROM EMP
ORDER BY DEPTNO DESC, ENAME ASC, SAL DESC;

-- 문제 33
SELECT ENAME, SAL, ROUND(SAL*0.13) BONUS, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- 문제 34
SELECT ENAME, SAL, NVL(COMM, 0), (SAL+NVL(COMM, 0)) TOTAL
FROM EMP
ORDER BY TOTAL DESC;

-- 문제 35
SELECT ENAME, SAL, TO_CHAR((SAL*0.15), '$999.9') 회비
FROM EMP
WHERE SAL BETWEEN 1500 AND 3000;

-- 문제 36
SELECT D.DNAME, COUNT(E.EMPNO)
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME
HAVING  COUNT(E.EMPNO) > 5;

-- 문제 37
SELECT JOB, SUM(SAL) 급여합계
FROM EMP
WHERE JOB != 'SALESMAN'
GROUP BY JOB
HAVING SUM(SAL) > 5000;

-- 문제 38
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- 문제 39
SELECT DEPTNO, COUNT(EMPNO) 사원수, COUNT(COMM) 커미션받은사원수
FROM EMP
GROUP BY DEPTNO;

-- 문제 40
SELECT ENAME, DEPTNO, CASE DEPTNO
WHEN 10 THEN '총무부'
WHEN 20 THEN '개발부'
WHEN 30 THEN '영업부'
END "부서명"
FROM EMP;