DESC EMP;

SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

SELECT *  FROM EMP WHERE SAL BETWEEN 2000 AND 3000;

CREATE TABLE EMP_TEMP AS
SELECT * FROM EMP WHERE 1 !=1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP
VALUES (9999, '홍길동', 'PRESIDENT', NULL, TO_DATE('01/01/01'),
5000, 1000, 10);

CREATE TABLE DEPT_TEMP2 AS
SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 40;

ROLLBACK;

SELECT * FROM EMP WHERE UPPER(ENAME) = 'SMITH';

SELECT * FROM EMP WHERE LENGTH(ENAME) <= 4;

SELECT SUBSTR(JOB, 0, 3) FROM EMP;

SELECT * FROM EMP WHERE HIREDATE >= '1981/06/01';

SELECT EMPNO, ENAME, SAL, COMM, 
(SAL*12)+NVL(COMM, 0) AS ANNSAL
FROM EMP;

SELECT COUNT(DISTINCT JOB) FROM EMP;

SELECT E.ENAME, D.DNAME
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.SAL >=3000;

SELECT * FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'MARTIN');

SELECT * FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);

SELECT *
FROM EMP E JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE S.GRADE = 3 AND E.DEPTNO = 30;

CREATE TABLE EMP_DDL (
EMPNO NUMBER(4,0), ENAME VARCHAR(10),
JOB VARCHAR(9), MGR NUMBER(4,0),
HIREDATE DATE, SAL NUMBER(7,2),
COMM NUMBER(7,2), DEPTNO NUMBER(2,0)
);

DESC EMP_DDL;

CREATE OR REPLACE VIEW EMP_V3
AS SELECT EMPNO 직원번호, ENAME 이름, JOB 직업,
HIREDATE 고용일자, SAL 월급, DEPTNO 부서번호
FROM EMP;